const GalleryWorks = [
  {
    img: "./preview/tetsim.gif",
    title: "Tetrahedral Simulation",
    link: "/simulation/tetsim",
    routePath: "tetsim",
    textColor: "text-white",
    bgColor: "",
  },
  {
    img: "./preview/water-refraction.gif",
    title: "Refraction Effect-2",
    link: "/gallery/refractioneffect-2",
    routePath: "refractioneffect-2",
    textColor: "text-white",
    bgColor: "",
  },
  {
    img: "./preview/modelcustomizer.gif",
    title: "Model Customizer",
    link: "/gallery/modelcustomizer",
    routePath: "modelcustomizer",
    textColor: "text-orange-500",
    bgColor: "",
  },
  {
    img: "./preview/shybirds.gif",
    title: "ShyBirds",
    link: "/gallery/shybirds",
    routePath: "shybirds",
    textColor: "text-orange-500",
    bgColor: "",
  },

  {
    img: "./preview/blossom.gif",
    title: "Typing Effect",
    link: "/gallery/typingeffect",
    routePath: "typingeffect",
    textColor: "text-white",
    bgColor: "",
  },
  {
    img: "./preview/mouseeffect.gif",
    title: "Mouse Effect",
    link: "/gallery/mouseeffect",
    routePath: "mouseeffect",
    textColor: "text-blue-500",
    bgColor: "",
  },
  {
    img: "./preview/confetti.gif",
    title: "Confetti Text",
    link: "/gallery/confettitext",
    routePath: "confettitext",
    textColor: "text-gray-900",
    bgColor: "",
  },
  {
    img: "./preview/ripple.gif",
    title: "Ripple",
    link: "/gallery/ripple",
    routePath: "ripple",
    textColor: "text-blue-500",
    bgColor: "",
  },

  {
    img: "./preview/glass-refraction.gif",
    title: "Refraction Effect",
    link: "/gallery/refractioneffect",
    routePath: "refractioneffect",
    textColor: "text-white",
    bgColor: "",
  },
  {
    img: "./preview/celestial.gif",
    title: "Celestial",
    link: "/gallery/celestial",
    routePath: "celestial",
    textColor: "text-white",
    bgColor: "",
  },

  {
    img: "./preview/particlemusic.gif",
    title: "Particle Music",
    link: "/gallery/particlemusic",
    routePath: "particlemusic",
    textColor: "text-white",
    bgColor: "",
  },
];

export default GalleryWorks;
